name: CI

on: push

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
    - name: prueba
      run: echo "Prueba"
  
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: prueba
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TOKEN }}
          approvers: josehilera
      - name: Deploy to production
        run: echo deploying

  build:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 1.8.x
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Build with Maven
        run: |
          mvn package
          pwd
          ls
        #working-directory: balontesto
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: baloncestohilera2
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.war

