name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 1.8.x
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Build with Maven
        run: ls
        #working-directory: balontesto
#      - name: Azure WebApp
#        uses: Azure/webapps-deploy@v2
#        with:
#          app-name: baloncestohilera
#          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#          package: Baloncesto/target/*.war

