name: CI

on: push

jobs:

  deploy:
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3
      - name: Instalar Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Crear el archivo .war
        run: |
          mvn package -DskipTests=true
          pwd
          ls target
#      - name: Aprobación manual
#      - uses: trstringer/manual-approval@v1
#        with:
#          secret: ${{ secrets.TOKEN }}
#          approvers: josehilera
      - name: Desplegar en Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: baloncesto-hilera
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.war


